// Placeholder sprite art, encoded as character strings.
//
// Convention (see palette.ts colorAt):
//   "."  transparent
//   "K"  outline / pure black
//   "@"  class accent — substituted by caller per Combatant
//   "0..3"  nature-theme tile palette (background dressing only)
//   "T,S,s,L,H,h,C,c"  body sprite slots (stem/leaf/petal/bark)
//
// These are crude prototypes. Real art replaces them with the same shape
// + better detail. Using inline strings means no asset pipeline yet.
//
// Tip: each line MUST be the same length as `size`. Reader trims newlines.

export interface PixelSprite {
  size: number;           // grid is size × size
  rows: readonly string[]; // length = size, each row length = size
}

function pack(art: string, size: number): PixelSprite {
  const rows = art.replace(/^\n/, '').replace(/\n$/, '').split('\n');
  if (rows.length !== size) {
    throw new Error(`sprite has ${rows.length} rows, expected ${size}`);
  }
  for (const r of rows) {
    if (r.length !== size) {
      throw new Error(`sprite row "${r}" has length ${r.length}, expected ${size}`);
    }
  }
  return { size, rows };
}

/* ─── 32x32 critter sprite — Bramble Sprite ────────────────────────
 * A small overgrown bramble-tangle with a wary leafy face. A wild
 * thing waiting to be soothed. PS-style chunk with outline pass.
 * Placeholder for real art. */
export const DRUNKEN_PATRON = pack(`
................................
................................
............KKKKKKK.............
...........KhhhhhhKK............
..........KhhhHHHHhKK...........
.........KhHHHHHHHHHKK..........
.........KHHsssssHHHK...........
........KHsssLLLsssHK...........
........KHsLLLLLLLsHK...........
........KHsLLKLLKLsHK...........
........KHsLLLLLLLsHK...........
........KHsLLLwLLsHK............
.........KHsLLLLLsHK............
..........KHssssHHK.............
.........KKHHHHHKK..............
........KCCCCCCCCCK.............
.......KCcccccccccCK............
.......KCcccccccccCK............
.......KCcccccccccCK............
.......KCccccc111ccCK...........
.......KCcccc11211ccK...........
.......KCcccc11211ccK...........
.......KCccccc111ccCK...........
........KCcccccccccK............
.........KCccccccCK.............
..........KCcccCK...............
...........KCCCK................
............KKK.................
.............K..................
.............K..................
............KKK.................
...........KKKKK................
`, 32);

/* ─── 32x32 critter sprite — Petal Sprite ──────────────────────────
 * Standing leaf-and-petal woodland critter, the generic tier-1 wild
 * thing the warden coaxes back to calm. */
export const BAR_PATRON = pack(`
................................
................................
............KKKKKKKK............
...........KhhhhhhhhK...........
..........KhhhhhhhhhhK..........
..........KhsssssssshK..........
.........KhsssLLLsssshK.........
.........KhsLLLLLLLLshK.........
.........KhsLLKLLKLLshK.........
.........KhsLLLLLLLLshK.........
.........KhsLLLLLLLshK..........
..........KhsssssshK............
...........KKHHHHKK.............
.........KCCCCCCCCCCK...........
........KcccccccccccCK..........
........KcccccccccccCK..........
........KcccccccccccCK..........
........KccccCCCccccCK..........
........KcccCCCCCCccCK..........
........KcccCCCCCCccCK..........
........KccccCCCccccCK..........
........KcccccccccccCK..........
........KcccccccccccCK..........
........KCKKKKKKKKKKCK..........
........KCK........KCK..........
........KCK........KCK..........
........KCK........KCK..........
........KKK........KKK..........
.......KKKK........KKKK.........
.....KKKKKK........KKKKKK.......
................................
................................
`, 32);

/* ─── 48x48 boss sprite — Guardian Tree (the grove's keeper) ─────────
 * A towering ancient tree-guardian, broad of trunk and crowned with
 * canopy. The wild heart of a place the warden must soothe. Placeholder. */
export const BAR_BOSS = pack(`
................................................
................................................
................KKKKKKKKKK......................
..............KKHHHHHHHHHHKK....................
.............KHHHHHHHHHHHHHHK...................
............KHHHHHHHHHHHHHHHHK..................
............KHsssssssssssssHHK..................
...........KHsssssLLLLLLsssssHK.................
...........KHsssLLLLLLLLLLLsssK.................
...........KHssLLLLLLLLLLLLLLsK.................
...........KHsLLKKLLLLLLLLKKLLK.................
...........KHsLLLLLLLLLLLLLLLLK.................
...........KHsLLLLL@@@@@@LLLLLK.................
...........KHsLLLLLL@@@@LLLLLLK.................
...........KHsLLLLLLLLLLLLLLsLK.................
...........KHsssLLLLLLLLLLLssK..................
............KHsssssssssssssK....................
.............KHHsssssssssHK.....................
............KKCCCCCCCCCCCCCKK...................
..........KKCccccccccccccccCCKK.................
.........KCccccccccccccccccccCK.................
........KCcccccccccccccccccccCK.................
........KCcccccccccccccccccccCK.................
........KCcccccccccccccccccccCK.................
........KCcccccccCCCCCCCccccccCK................
........KCccccccCCCCCCCCCcccccCK................
........KCccccccCC@@@@@@CCccccCK................
........KCccccccCC@@@@@@CCccccCK................
........KCccccccCCCCCCCCCCccccCK................
........KCcccccccccccccccccccCK.................
........KCcccccccccccccccccccCK.................
........KCcccccccccccccccccccCK.................
........KCcccccccccccccccccccCK.................
........KCKKKKKKKKKKKKKKKKKKKCK.................
........KCK................KCK..................
........KCK................KCK..................
........KCK................KCK..................
........KCK................KCK..................
........KKK................KKK..................
.......KKKK................KKKK.................
......KKKKK................KKKKK................
.....KKKK....................KKKK...............
................................................
................................................
................................................
................................................
................................................
................................................
`, 48);

export const SPRITES = {
  drunken_patron: DRUNKEN_PATRON,
  bar_patron: BAR_PATRON,
  bar_boss: BAR_BOSS,
} as const;

export type SpriteId = keyof typeof SPRITES;
